### ISSUE TITLE
Use of numy distutils

### ISSUE THREAD

**Issue by wolfidan** [MeteoSwiss/pyrad#17]
Numpy distutils that is used in pyrad’s setup.py will be deprecated in python 3.12.
Already now it relies on outdated libraries and I sometimes have issues with it.
The question is should we use setuptools as pyart ? One disadvantage is that it does not have the nested setup.py, which are used at the moment in pyrad.
The question is how important are those nested setup.py files ? Should we move to setuptools?

**Comment by jfigui** [comment]
Hi @wolfidan,

According to https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration setuptools should do the job since it also handles nested setup.py files. When I created this setup.py file I was blindly following the ARM-DOE Py-ART way of doing things so I assume a similar configuration to what they have now should also work for us.
